#!/bin/sh
if [ "$1" == "" ]; then
    for UIFILE in *.ui; do
	UIFILE=${UIFILE:0:${#UIFILE}-3}
	echo Compiling $UIFILE...
	uic -o $UIFILE.h $UIFILE.ui;
	uic -o $UIFILE.cpp -tr i18n -impl $UIFILE.h $UIFILE.ui;
    done;
else
    UIFILE=$1
    UIFILE=${UIFILE:0:${#UIFILE}-3}
    echo Compiling $UIFILE...
    uic -o $UIFILE.h $UIFILE.ui;
    uic -o $UIFILE.cpp -tr i18n -impl $UIFILE.h $UIFILE.ui;
fi
